//
//  Category.swift
//  Yelp
//
//  Created by chengyin_liu on 5/23/16.
//  Copyright © 2016 Timothy Lee. All rights reserved.
//

import Foundation

struct Category: Hashable {
  let code: String
  var name: String? {
    return CATEGORIES[code];
  }

  var hashValue: Int {
    return code.hashValue
  }

  static var all: [Category] {
    var categories:[Category] = []

    for (code, _) in CATEGORIES {
      categories.append(Category(code: code));
    }

    return categories.sort({ (c1, c2) -> Bool in
      c1.name < c2.name
    })
  }
}

func ==(lhs: Category, rhs: Category) -> Bool {
  return lhs.code == rhs.code;
}

let CATEGORIES = [
  "afghani": "Afghan",
  "african": "African",
  "newamerican": "American, New",
  "tradamerican": "American, Traditional",
  "arabian": "Arabian",
  "argentine": "Argentine",
  "armenian": "Armenian",
  "asianfusion": "Asian Fusion",
  "asturian": "Asturian",
  "australian": "Australian",
  "austrian": "Austrian",
  "baguettes": "Baguettes",
  "bangladeshi": "Bangladeshi",
  "bbq": "Barbeque",
  "basque": "Basque",
  "bavarian": "Bavarian",
  "beergarden": "Beer Garden",
  "beerhall": "Beer Hall",
  "beisl": "Beisl",
  "belgian": "Belgian",
  "bistros": "Bistros",
  "blacksea": "Black Sea",
  "brasseries": "Brasseries",
  "brazilian": "Brazilian",
  "breakfast_brunch": "Breakfast & Brunch",
  "british": "British",
  "buffets": "Buffets",
  "bulgarian": "Bulgarian",
  "burgers": "Burgers",
  "burmese": "Burmese",
  "cafes": "Cafes",
  "cafeteria": "Cafeteria",
  "cajun": "Cajun/Creole",
  "cambodian": "Cambodian",
  "New)": "Canadian",
  "canteen": "Canteen",
  "caribbean": "Caribbean",
  "catalan": "Catalan",
  "chech": "Chech",
  "cheesesteaks": "Cheesesteaks",
  "chickenshop": "Chicken Shop",
  "chicken_wings": "Chicken Wings",
  "chilean": "Chilean",
  "chinese": "Chinese",
  "comfortfood": "Comfort Food",
  "corsican": "Corsican",
  "creperies": "Creperies",
  "cuban": "Cuban",
  "currysausage": "Curry Sausage",
  "cypriot": "Cypriot",
  "czech": "Czech",
  "czechslovakian": "Czech/Slovakian",
  "danish": "Danish",
  "delis": "Delis",
  "diners": "Diners",
  "dumplings": "Dumplings",
  "eastern_european": "Eastern European",
  "ethiopian": "Ethiopian",
  "hotdogs": "Fast Food",
  "filipino": "Filipino",
  "fishnchips": "Fish & Chips",
  "fondue": "Fondue",
  "food_court": "Food Court",
  "foodstands": "Food Stands",
  "french": "French",
  "sud_ouest": "French Southwest",
  "galician": "Galician",
  "gastropubs": "Gastropubs",
  "georgian": "Georgian",
  "german": "German",
  "giblets": "Giblets",
  "gluten_free": "Gluten-Free",
  "greek": "Greek",
  "halal": "Halal",
  "hawaiian": "Hawaiian",
  "heuriger": "Heuriger",
  "himalayan": "Himalayan/Nepalese",
  "hkcafe": "Hong Kong Style Cafe",
  "hotdog": "Hot Dogs",
  "hotpot": "Hot Pot",
  "hungarian": "Hungarian",
  "iberian": "Iberian",
  "indpak": "Indian",
  "indonesian": "Indonesian",
  "international": "International",
  "irish": "Irish",
  "island_pub": "Island Pub",
  "israeli": "Israeli",
  "italian": "Italian",
  "japanese": "Japanese",
  "jewish": "Jewish",
  "kebab": "Kebab",
  "korean": "Korean",
  "kosher": "Kosher",
  "kurdish": "Kurdish",
  "laos": "Laos",
  "laotian": "Laotian",
  "latin": "Latin American",
  "raw_food": "Live/Raw Food",
  "lyonnais": "Lyonnais",
  "malaysian": "Malaysian",
  "meatballs": "Meatballs",
  "mediterranean": "Mediterranean",
  "mexican": "Mexican",
  "mideastern": "Middle Eastern",
  "milkbars": "Milk Bars",
  "modern_australian": "Modern Australian",
  "modern_european": "Modern European",
  "mongolian": "Mongolian",
  "moroccan": "Moroccan",
  "newzealand": "New Zealand",
  "nightfood": "Night Food",
  "norcinerie": "Norcinerie",
  "opensandwiches": "Open Sandwiches",
  "oriental": "Oriental",
  "pakistani": "Pakistani",
  "eltern_cafes": "Parent Cafes",
  "parma": "Parma",
  "persian": "Persian/Iranian",
  "peruvian": "Peruvian",
  "pita": "Pita",
  "pizza": "Pizza",
  "polish": "Polish",
  "portuguese": "Portuguese",
  "potatoes": "Potatoes",
  "poutineries": "Poutineries",
  "pubfood": "Pub Food",
  "riceshop": "Rice",
  "romanian": "Romanian",
  "rotisserie_chicken": "Rotisserie Chicken",
  "rumanian": "Rumanian",
  "russian": "Russian",
  "salad": "Salad",
  "sandwiches": "Sandwiches",
  "scandinavian": "Scandinavian",
  "scottish": "Scottish",
  "seafood": "Seafood",
  "serbocroatian": "Serbo Croatian",
  "signature_cuisine": "Signature Cuisine",
  "singaporean": "Singaporean",
  "slovakian": "Slovakian",
  "soulfood": "Soul Food",
  "soup": "Soup",
  "southern": "Southern",
  "spanish": "Spanish",
  "steak": "Steakhouses",
  "sushi": "Sushi Bars",
  "swabian": "Swabian",
  "swedish": "Swedish",
  "swissfood": "Swiss Food",
  "tabernas": "Tabernas",
  "taiwanese": "Taiwanese",
  "tapas": "Tapas Bars",
  "tapasmallplates": "Tapas/Small Plates",
  "tex-mex": "Tex-Mex",
  "thai": "Thai",
  "norwegian": "Traditional Norwegian",
  "traditional_swedish": "Traditional Swedish",
  "trattorie": "Trattorie",
  "turkish": "Turkish",
  "ukrainian": "Ukrainian",
  "uzbek": "Uzbek",
  "vegan": "Vegan",
  "vegetarian": "Vegetarian",
  "venison": "Venison",
  "vietnamese": "Vietnamese",
  "wok": "Wok",
  "wraps": "Wraps",
  "name" : "Yugoslav", "code": "yugoslav"
];

//let CATEGORIES = [
//  ["name" : "Afghan", "code": "afghani"],
//  ["name" : "African", "code": "african"],
//  ["name" : "American, New", "code": "newamerican"],
//  ["name" : "American, Traditional", "code": "tradamerican"],
//  ["name" : "Arabian", "code": "arabian"],
//  ["name" : "Argentine", "code": "argentine"],
//  ["name" : "Armenian", "code": "armenian"],
//  ["name" : "Asian Fusion", "code": "asianfusion"],
//  ["name" : "Asturian", "code": "asturian"],
//  ["name" : "Australian", "code": "australian"],
//  ["name" : "Austrian", "code": "austrian"],
//  ["name" : "Baguettes", "code": "baguettes"],
//  ["name" : "Bangladeshi", "code": "bangladeshi"],
//  ["name" : "Barbeque", "code": "bbq"],
//  ["name" : "Basque", "code": "basque"],
//  ["name" : "Bavarian", "code": "bavarian"],
//  ["name" : "Beer Garden", "code": "beergarden"],
//  ["name" : "Beer Hall", "code": "beerhall"],
//  ["name" : "Beisl", "code": "beisl"],
//  ["name" : "Belgian", "code": "belgian"],
//  ["name" : "Bistros", "code": "bistros"],
//  ["name" : "Black Sea", "code": "blacksea"],
//  ["name" : "Brasseries", "code": "brasseries"],
//  ["name" : "Brazilian", "code": "brazilian"],
//  ["name" : "Breakfast & Brunch", "code": "breakfast_brunch"],
//  ["name" : "British", "code": "british"],
//  ["name" : "Buffets", "code": "buffets"],
//  ["name" : "Bulgarian", "code": "bulgarian"],
//  ["name" : "Burgers", "code": "burgers"],
//  ["name" : "Burmese", "code": "burmese"],
//  ["name" : "Cafes", "code": "cafes"],
//  ["name" : "Cafeteria", "code": "cafeteria"],
//  ["name" : "Cajun/Creole", "code": "cajun"],
//  ["name" : "Cambodian", "code": "cambodian"],
//  ["name" : "Canadian", "code": "New)"],
//  ["name" : "Canteen", "code": "canteen"],
//  ["name" : "Caribbean", "code": "caribbean"],
//  ["name" : "Catalan", "code": "catalan"],
//  ["name" : "Chech", "code": "chech"],
//  ["name" : "Cheesesteaks", "code": "cheesesteaks"],
//  ["name" : "Chicken Shop", "code": "chickenshop"],
//  ["name" : "Chicken Wings", "code": "chicken_wings"],
//  ["name" : "Chilean", "code": "chilean"],
//  ["name" : "Chinese", "code": "chinese"],
//  ["name" : "Comfort Food", "code": "comfortfood"],
//  ["name" : "Corsican", "code": "corsican"],
//  ["name" : "Creperies", "code": "creperies"],
//  ["name" : "Cuban", "code": "cuban"],
//  ["name" : "Curry Sausage", "code": "currysausage"],
//  ["name" : "Cypriot", "code": "cypriot"],
//  ["name" : "Czech", "code": "czech"],
//  ["name" : "Czech/Slovakian", "code": "czechslovakian"],
//  ["name" : "Danish", "code": "danish"],
//  ["name" : "Delis", "code": "delis"],
//  ["name" : "Diners", "code": "diners"],
//  ["name" : "Dumplings", "code": "dumplings"],
//  ["name" : "Eastern European", "code": "eastern_european"],
//  ["name" : "Ethiopian", "code": "ethiopian"],
//  ["name" : "Fast Food", "code": "hotdogs"],
//  ["name" : "Filipino", "code": "filipino"],
//  ["name" : "Fish & Chips", "code": "fishnchips"],
//  ["name" : "Fondue", "code": "fondue"],
//  ["name" : "Food Court", "code": "food_court"],
//  ["name" : "Food Stands", "code": "foodstands"],
//  ["name" : "French", "code": "french"],
//  ["name" : "French Southwest", "code": "sud_ouest"],
//  ["name" : "Galician", "code": "galician"],
//  ["name" : "Gastropubs", "code": "gastropubs"],
//  ["name" : "Georgian", "code": "georgian"],
//  ["name" : "German", "code": "german"],
//  ["name" : "Giblets", "code": "giblets"],
//  ["name" : "Gluten-Free", "code": "gluten_free"],
//  ["name" : "Greek", "code": "greek"],
//  ["name" : "Halal", "code": "halal"],
//  ["name" : "Hawaiian", "code": "hawaiian"],
//  ["name" : "Heuriger", "code": "heuriger"],
//  ["name" : "Himalayan/Nepalese", "code": "himalayan"],
//  ["name" : "Hong Kong Style Cafe", "code": "hkcafe"],
//  ["name" : "Hot Dogs", "code": "hotdog"],
//  ["name" : "Hot Pot", "code": "hotpot"],
//  ["name" : "Hungarian", "code": "hungarian"],
//  ["name" : "Iberian", "code": "iberian"],
//  ["name" : "Indian", "code": "indpak"],
//  ["name" : "Indonesian", "code": "indonesian"],
//  ["name" : "International", "code": "international"],
//  ["name" : "Irish", "code": "irish"],
//  ["name" : "Island Pub", "code": "island_pub"],
//  ["name" : "Israeli", "code": "israeli"],
//  ["name" : "Italian", "code": "italian"],
//  ["name" : "Japanese", "code": "japanese"],
//  ["name" : "Jewish", "code": "jewish"],
//  ["name" : "Kebab", "code": "kebab"],
//  ["name" : "Korean", "code": "korean"],
//  ["name" : "Kosher", "code": "kosher"],
//  ["name" : "Kurdish", "code": "kurdish"],
//  ["name" : "Laos", "code": "laos"],
//  ["name" : "Laotian", "code": "laotian"],
//  ["name" : "Latin American", "code": "latin"],
//  ["name" : "Live/Raw Food", "code": "raw_food"],
//  ["name" : "Lyonnais", "code": "lyonnais"],
//  ["name" : "Malaysian", "code": "malaysian"],
//  ["name" : "Meatballs", "code": "meatballs"],
//  ["name" : "Mediterranean", "code": "mediterranean"],
//  ["name" : "Mexican", "code": "mexican"],
//  ["name" : "Middle Eastern", "code": "mideastern"],
//  ["name" : "Milk Bars", "code": "milkbars"],
//  ["name" : "Modern Australian", "code": "modern_australian"],
//  ["name" : "Modern European", "code": "modern_european"],
//  ["name" : "Mongolian", "code": "mongolian"],
//  ["name" : "Moroccan", "code": "moroccan"],
//  ["name" : "New Zealand", "code": "newzealand"],
//  ["name" : "Night Food", "code": "nightfood"],
//  ["name" : "Norcinerie", "code": "norcinerie"],
//  ["name" : "Open Sandwiches", "code": "opensandwiches"],
//  ["name" : "Oriental", "code": "oriental"],
//  ["name" : "Pakistani", "code": "pakistani"],
//  ["name" : "Parent Cafes", "code": "eltern_cafes"],
//  ["name" : "Parma", "code": "parma"],
//  ["name" : "Persian/Iranian", "code": "persian"],
//  ["name" : "Peruvian", "code": "peruvian"],
//  ["name" : "Pita", "code": "pita"],
//  ["name" : "Pizza", "code": "pizza"],
//  ["name" : "Polish", "code": "polish"],
//  ["name" : "Portuguese", "code": "portuguese"],
//  ["name" : "Potatoes", "code": "potatoes"],
//  ["name" : "Poutineries", "code": "poutineries"],
//  ["name" : "Pub Food", "code": "pubfood"],
//  ["name" : "Rice", "code": "riceshop"],
//  ["name" : "Romanian", "code": "romanian"],
//  ["name" : "Rotisserie Chicken", "code": "rotisserie_chicken"],
//  ["name" : "Rumanian", "code": "rumanian"],
//  ["name" : "Russian", "code": "russian"],
//  ["name" : "Salad", "code": "salad"],
//  ["name" : "Sandwiches", "code": "sandwiches"],
//  ["name" : "Scandinavian", "code": "scandinavian"],
//  ["name" : "Scottish", "code": "scottish"],
//  ["name" : "Seafood", "code": "seafood"],
//  ["name" : "Serbo Croatian", "code": "serbocroatian"],
//  ["name" : "Signature Cuisine", "code": "signature_cuisine"],
//  ["name" : "Singaporean", "code": "singaporean"],
//  ["name" : "Slovakian", "code": "slovakian"],
//  ["name" : "Soul Food", "code": "soulfood"],
//  ["name" : "Soup", "code": "soup"],
//  ["name" : "Southern", "code": "southern"],
//  ["name" : "Spanish", "code": "spanish"],
//  ["name" : "Steakhouses", "code": "steak"],
//  ["name" : "Sushi Bars", "code": "sushi"],
//  ["name" : "Swabian", "code": "swabian"],
//  ["name" : "Swedish", "code": "swedish"],
//  ["name" : "Swiss Food", "code": "swissfood"],
//  ["name" : "Tabernas", "code": "tabernas"],
//  ["name" : "Taiwanese", "code": "taiwanese"],
//  ["name" : "Tapas Bars", "code": "tapas"],
//  ["name" : "Tapas/Small Plates", "code": "tapasmallplates"],
//  ["name" : "Tex-Mex", "code": "tex-mex"],
//  ["name" : "Thai", "code": "thai"],
//  ["name" : "Traditional Norwegian", "code": "norwegian"],
//  ["name" : "Traditional Swedish", "code": "traditional_swedish"],
//  ["name" : "Trattorie", "code": "trattorie"],
//  ["name" : "Turkish", "code": "turkish"],
//  ["name" : "Ukrainian", "code": "ukrainian"],
//  ["name" : "Uzbek", "code": "uzbek"],
//  ["name" : "Vegan", "code": "vegan"],
//  ["name" : "Vegetarian", "code": "vegetarian"],
//  ["name" : "Venison", "code": "venison"],
//  ["name" : "Vietnamese", "code": "vietnamese"],
//  ["name" : "Wok", "code": "wok"],
//  ["name" : "Wraps", "code": "wraps"],
//  ["name" : "Yugoslav", "code": "yugoslav"]
//];